<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.7.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NVUpdateManager.Core\NVUpdateManager.Core.csproj" />
  </ItemGroup>
</Project>