# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Deploy

on:
  push:
    tags:
      - '*'

jobs:
        
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build NotificationService project
        run: dotnet build -c Release --no-restore
      - name: Compress archive
        run: Compress-Archive -Path .\NVUpdateManager.NotificationService\bin\Release\* -DestinationPath .\NVUpdateManager.NotificationService.zip -CompressionLevel Fastest
      - name: Generate Release Notes
        run: git log -1 --pretty=%B > ${{ github.workspace }}-CHANGELOG.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            README.md
            LICENSE
            NVUpdateManager.NotificationService.zip
          token: ${{ secrets.GITHUB_TOKEN }}
